### ISSUE TITLE
[feature request]: Stream line copy right note for the entire solution

### ISSUE THREAD

**Issue by maythamfahmi** [maythamfahmi/CryptoNet#105]
### Is your feature request related to a problem? Please describe.

na

### Describe the solution you'd like

streamline the copyright note so it is consestant all the way 

### Priority Level

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jwdonahue** [comment]
"streamline copyright notice" is a bit vague.

**Comment by maythamfahmi** [comment]
When I look back on this feature, I agree I will close it and if future change needed in futre we make a new feature 😃

**Comment by jwdonahue** [comment]
So, I do have some concerns about some of the copyright notices in the source code, that do not mention the license. I am not lawyer, I especially do not grok international law, but I don't think any copyright or license notices are strictly required at the individual file levels, particularly where the content creator can be identified by reviewing the repo history.

I've adopted the habit of putting a single line at the top of all my source files, that never needs to be changed again, that references the end of the file, where any copyright, license or other notices might be placed. I prefer that, because any changes at the end of a file, are much less likely to trigger merge conflicts, and reviewers/maintainers have less clutter to wade through, when all they want to see is the code.

**Comment by jwdonahue** [comment]
I would add that I do not see this as a critical issue in this code base.

I do worry somewhat that some of the existing notices, seem to imply that some company called "NextBix" has copyright notices with full reservations, and does not appear to have issued any license notices.

**Comment by maythamfahmi** [comment]
@jwdonahue I agree, it is not critical. In regards to NextBix! it is just my hobby business name. but it is https://nextbix.dk.
